environments:
    benrd: 
    kylerd:
    adamrd:
    marcusrd:
    ericrd:
    pondrd:
    #USING INT, MAIN AND SPRINT TO REFLECT OUR INTEGRATION (PR VERSION), MAIN (REFLECTING MAIN BRANCH), SPRINT (STATIC RELEASE VERSION FOR SPRINT REVIEW)
    int:
    main:
    sprint:
    prod-blue:
    prod-green: 
    dev:
    prototype:

releases:
# lifejourneys
  - name: lifejourneys-{{ .Environment.Name }}
    chart: ../helm/charts/lifejourneys
    version: 0.0.1
    values:
      - overrides/lifejourneys.yaml.gotmpl
    labels:
        category: dts
        app: lifejourneys
        tier: server
    namespace: lifejourneys-{{ .Environment.Name }}
    installed: true
    wait: false
    force: false
