export default [
    { value: "CAN", label: "https://www.canada.ca/en.html" },
    { value: "AB", label: "https://www.alberta.ca/index.aspx" },
    { value: "BC", label: "https://www2.gov.bc.ca/gov/content/home" },
    { value: "MB", label: "https://www.gov.mb.ca/" },
    { value: "NB", label: "https://www2.gnb.ca/" },
    { value: "NL", label: "https://www.gov.nl.ca/" },
    { value: "NT", label: "https://www.gov.nt.ca/" },
    { value: "NS", label: "https://beta.novascotia.ca/" },
    { value: "NU", label: "https://gov.nu.ca/" },
    { value: "ON", label: "https://www.ontario.ca/page/government-ontario" },
    { value: "PE", label: "https://www.princeedwardisland.ca/en" },
    { value: "QC", label: "https://www.quebec.ca/en/" },
    { value: "SK", label: "https://www.saskatchewan.ca/" },
    { value: "YT", label: "https://yukon.ca/" },
  ];